import type { AvatarItem } from '@/types'

export const AVATAR_ITEMS: AvatarItem[] = [
  // === 髪型・髪色 ===
  {
    id: 'hair-pink-long',
    name: 'ピンクのロングヘア',
    category: 'hair',
    gender: 'girl',
    pointsCost: 50,
    rarity: 'common',
    description: 'かわいいピンクのロングヘア',
    avatarChanges: { hairColor: '#FF69B4', hairStyle: 'womanLong' },
    sortOrder: 1,
  },
  {
    id: 'hair-purple-long',
    name: 'むらさきのロングヘア',
    category: 'hair',
    gender: 'girl',
    pointsCost: 100,
    rarity: 'rare',
    description: 'まほうつかいみたいなむらさきヘア',
    avatarChanges: { hairColor: '#9370DB', hairStyle: 'womanLong' },
    sortOrder: 2,
  },
  {
    id: 'hair-blue-long',
    name: 'ブルーのロングヘア',
    category: 'hair',
    gender: 'girl',
    pointsCost: 100,
    rarity: 'rare',
    description: 'うみみたいなきれいなブルーヘア',
    avatarChanges: { hairColor: '#87CEEB', hairStyle: 'womanLong' },
    sortOrder: 3,
  },
  {
    id: 'hair-gold-short',
    name: 'ゴールドのショートヘア',
    category: 'hair',
    gender: 'girl',
    pointsCost: 80,
    rarity: 'common',
    description: 'きらきらのゴールドショートヘア',
    avatarChanges: { hairColor: '#FFD700', hairStyle: 'womanShort' },
    sortOrder: 4,
  },
  {
    id: 'hair-red-short',
    name: 'レッドのショートヘア',
    category: 'hair',
    gender: 'both',
    pointsCost: 80,
    rarity: 'common',
    description: 'げんきなあかいショートヘア',
    avatarChanges: { hairColor: '#FF4500', hairStyle: 'womanShort' },
    sortOrder: 5,
  },
  {
    id: 'hair-rainbow',
    name: 'レインボーヘア',
    category: 'hair',
    gender: 'girl',
    pointsCost: 300,
    rarity: 'epic',
    description: 'にじいろのまほうのヘア✨',
    avatarChanges: { hairColor: '#FF6B9D', hairStyle: 'womanLong' },
    sortOrder: 6,
  },

  // === 帽子 ===
  {
    id: 'hat-pink-beanie',
    name: 'ピンクのニット帽',
    category: 'hat',
    gender: 'both',
    pointsCost: 120,
    rarity: 'rare',
    description: 'ふわふわのピンクニット帽',
    avatarChanges: { hatStyle: 'beanie', hatColor: '#FF69B4' },
    sortOrder: 10,
  },
  {
    id: 'hat-green-beanie',
    name: 'みどりのニット帽',
    category: 'hat',
    gender: 'both',
    pointsCost: 120,
    rarity: 'rare',
    description: 'もりのようなみどりニット帽',
    avatarChanges: { hatStyle: 'beanie', hatColor: '#90EE90' },
    sortOrder: 11,
  },
  {
    id: 'hat-gold-turban',
    name: 'おうじょのターバン',
    category: 'hat',
    gender: 'girl',
    pointsCost: 250,
    rarity: 'epic',
    description: 'おうじょさまみたいなきんのターバン👑',
    avatarChanges: { hatStyle: 'turban', hatColor: '#FFD700' },
    sortOrder: 12,
  },

  // === 目 ===
  {
    id: 'eyes-smile',
    name: 'にっこり目',
    category: 'eyes',
    gender: 'both',
    pointsCost: 60,
    rarity: 'common',
    description: 'にっこりとかわいい目',
    avatarChanges: { eyeStyle: 'smile' },
    sortOrder: 20,
  },
  {
    id: 'eyes-oval',
    name: 'たれ目',
    category: 'eyes',
    gender: 'both',
    pointsCost: 60,
    rarity: 'common',
    description: 'おっとりしたやさしいたれ目',
    avatarChanges: { eyeStyle: 'oval' },
    sortOrder: 21,
  },

  // === メガネ ===
  {
    id: 'glasses-round',
    name: 'まるメガネ',
    category: 'glasses',
    gender: 'both',
    pointsCost: 80,
    rarity: 'rare',
    description: 'かわいいまるいメガネ',
    avatarChanges: { glassesStyle: 'round' },
    sortOrder: 30,
  },
  {
    id: 'glasses-square',
    name: 'しかくメガネ',
    category: 'glasses',
    gender: 'both',
    pointsCost: 80,
    rarity: 'rare',
    description: 'かっこいいしかくいメガネ',
    avatarChanges: { glassesStyle: 'square' },
    sortOrder: 31,
  },

  // === 口 ===
  {
    id: 'mouth-laugh',
    name: 'わらいぐち',
    category: 'mouth',
    gender: 'both',
    pointsCost: 50,
    rarity: 'common',
    description: 'おおきくわらっているお口',
    avatarChanges: { mouthStyle: 'laugh' },
    sortOrder: 40,
  },
  {
    id: 'mouth-peace',
    name: 'てへぺろ',
    category: 'mouth',
    gender: 'both',
    pointsCost: 70,
    rarity: 'common',
    description: 'かわいいてへぺろ顔',
    avatarChanges: { mouthStyle: 'peace' },
    sortOrder: 41,
  },

  // === シャツ ===
  {
    id: 'shirt-red-hoody',
    name: 'あかいパーカー',
    category: 'shirt',
    gender: 'both',
    pointsCost: 100,
    rarity: 'common',
    description: 'げんきなあかいパーカー',
    avatarChanges: { shirtStyle: 'hoody', shirtColor: '#FF6B6B' },
    sortOrder: 50,
  },
  {
    id: 'shirt-yellow-hoody',
    name: 'きいろいパーカー',
    category: 'shirt',
    gender: 'both',
    pointsCost: 100,
    rarity: 'common',
    description: 'たのしいきいろいパーカー',
    avatarChanges: { shirtStyle: 'hoody', shirtColor: '#FFD93D' },
    sortOrder: 51,
  },
  {
    id: 'shirt-purple-polo',
    name: 'むらさきポロシャツ',
    category: 'shirt',
    gender: 'both',
    pointsCost: 120,
    rarity: 'rare',
    description: 'おしゃれなむらさきポロシャツ',
    avatarChanges: { shirtStyle: 'polo', shirtColor: '#9B59B6' },
    sortOrder: 52,
  },
  {
    id: 'shirt-rainbow-hoody',
    name: 'レインボーパーカー',
    category: 'shirt',
    gender: 'both',
    pointsCost: 250,
    rarity: 'epic',
    description: 'にじいろのかがやくパーカー✨',
    avatarChanges: { shirtStyle: 'hoody', shirtColor: '#FF6B9D' },
    sortOrder: 53,
  },

  // === 背景 ===
  {
    id: 'bg-pink',
    name: 'ピンクのせかい',
    category: 'background',
    gender: 'both',
    pointsCost: 80,
    rarity: 'common',
    description: 'ピンクいろのかわいい背景',
    avatarChanges: { bgColor: '#FFB3DE' },
    sortOrder: 60,
  },
  {
    id: 'bg-sky',
    name: 'そらいろのせかい',
    category: 'background',
    gender: 'both',
    pointsCost: 80,
    rarity: 'common',
    description: 'きれいなそら色の背景',
    avatarChanges: { bgColor: '#87CEEB' },
    sortOrder: 61,
  },
  {
    id: 'bg-star',
    name: 'ほしぞらのせかい',
    category: 'background',
    gender: 'both',
    pointsCost: 200,
    rarity: 'epic',
    description: 'きらきらのほしぞら背景✨',
    avatarChanges: { bgColor: '#1A1A2E' },
    sortOrder: 62,
  },
]

export const DEFAULT_GIRL_AVATAR: import('@/types').AvatarConfig = {
  sex: 'woman',
  faceColor: '#F9C9B6',
  earSize: 'small',
  hairColor: '#FC909F',
  hairStyle: 'womanLong',
  hatColor: '#ffffff',
  hatStyle: 'none',
  eyeStyle: 'circle',
  glassesStyle: 'none',
  noseStyle: 'short',
  mouthStyle: 'smile',
  shirtStyle: 'short',
  shirtColor: '#9BD0E0',
  bgColor: '#FFDEB0',
}

export const DEFAULT_BOY_AVATAR: import('@/types').AvatarConfig = {
  sex: 'man',
  faceColor: '#F9C9B6',
  earSize: 'small',
  hairColor: '#77311D',
  hairStyle: 'normal',
  hatColor: '#ffffff',
  hatStyle: 'none',
  eyeStyle: 'circle',
  glassesStyle: 'none',
  noseStyle: 'short',
  mouthStyle: 'smile',
  shirtStyle: 'short',
  shirtColor: '#6BD9E9',
  bgColor: '#B0E2FF',
}

export const CATEGORY_LABELS: Record<string, string> = {
  hair: '💇 ヘアスタイル',
  hat: '🎩 ぼうし',
  eyes: '👀 め',
  glasses: '👓 めがね',
  mouth: '😊 くち',
  shirt: '👕 シャツ',
  background: '🌈 はいけい',
}

export const RARITY_LABELS: Record<string, { label: string; color: string }> = {
  common: { label: 'ふつう', color: 'text-gray-500' },
  rare: { label: 'レア', color: 'text-blue-500' },
  epic: { label: 'エピック', color: 'text-purple-500' },
}
