import type { AppState } from '@/types'
import { AVATAR_ITEMS, DEFAULT_GIRL_AVATAR } from './avatar-items'
import { format, subDays } from 'date-fns'

const today = format(new Date(), 'yyyy-MM-dd')
const yesterday = format(subDays(new Date(), 1), 'yyyy-MM-dd')

export const DEMO_STATE: AppState = {
  families: [
    {
      id: 'family-1',
      name: '村上家',
      inviteCode: 'KIKO01',
      createdAt: '2026-03-01T00:00:00Z',
    },
  ],
  profiles: [
    {
      id: 'parent-papa',
      familyId: 'family-1',
      name: 'パパ',
      role: 'parent',
      gender: 'boy',
      avatarConfig: {
        sex: 'man',
        faceColor: '#F9C9B6',
        earSize: 'small',
        hairColor: '#77311D',
        hairStyle: 'normal',
        hatColor: '#ffffff',
        hatStyle: 'none',
        eyeStyle: 'circle',
        glassesStyle: 'none',
        noseStyle: 'short',
        mouthStyle: 'smile',
        shirtStyle: 'polo',
        shirtColor: '#3498DB',
        bgColor: '#B0E2FF',
      },
      pointsTotal: 0,
      picturePassword: null,
      passwordHash: 'papa123',
      createdAt: '2026-03-01T00:00:00Z',
    },
    {
      id: 'parent-mama',
      familyId: 'family-1',
      name: 'ママ',
      role: 'parent',
      gender: 'girl',
      avatarConfig: {
        sex: 'woman',
        faceColor: '#F9C9B6',
        earSize: 'small',
        hairColor: '#FC909F',
        hairStyle: 'womanShort',
        hatColor: '#ffffff',
        hatStyle: 'none',
        eyeStyle: 'oval',
        glassesStyle: 'none',
        noseStyle: 'short',
        mouthStyle: 'smile',
        shirtStyle: 'short',
        shirtColor: '#FF69B4',
        bgColor: '#FFB3DE',
      },
      pointsTotal: 0,
      picturePassword: null,
      passwordHash: 'kino123',
      createdAt: '2026-03-01T00:00:00Z',
    },
    {
      id: 'child-kiko',
      familyId: 'family-1',
      name: 'きこ',
      role: 'child',
      gender: 'girl',
      avatarConfig: {
        ...DEFAULT_GIRL_AVATAR,
        hairColor: '#FF69B4',
        bgColor: '#FFB3DE',
        shirtColor: '#FF6B6B',
        shirtStyle: 'hoody',
      },
      pointsTotal: 230,
      picturePassword: ['🐱', '🐰', '🐻'],
      passwordHash: null,
      createdAt: '2026-03-01T00:00:00Z',
    },
  ],
  tasks: [
    {
      id: 'task-1',
      familyId: 'family-1',
      createdBy: 'parent-papa',
      assignedTo: 'child-kiko',
      title: '自分で起きる',
      description: 'めざましで自分で起きよう！',
      category: 'routine',
      pointsValue: 15,
      frequency: 'weekday',
      scheduledTime: '06:30',
      isActive: true,
      emoji: '⏰',
      createdAt: '2026-03-01T00:00:00Z',
    },
    {
      id: 'task-2',
      familyId: 'family-1',
      createdBy: 'parent-papa',
      assignedTo: 'child-kiko',
      title: 'ごはんを食べる',
      description: '朝ごはんをしっかり食べよう',
      category: 'routine',
      pointsValue: 10,
      frequency: 'daily',
      scheduledTime: '07:00',
      isActive: true,
      emoji: '🍱',
      createdAt: '2026-03-01T00:00:00Z',
    },
    {
      id: 'task-3',
      familyId: 'family-1',
      createdBy: 'parent-papa',
      assignedTo: 'child-kiko',
      title: '支度をする',
      description: 'ランドセルの準備・着替えをしよう',
      category: 'routine',
      pointsValue: 10,
      frequency: 'weekday',
      scheduledTime: '07:15',
      isActive: true,
      emoji: '🎒',
      createdAt: '2026-03-01T00:00:00Z',
    },
    {
      id: 'task-4',
      familyId: 'family-1',
      createdBy: 'parent-mama',
      assignedTo: 'child-kiko',
      title: 'たぴのごはん',
      description: 'たぴにごはんをあげよう',
      category: 'chore',
      pointsValue: 15,
      frequency: 'daily',
      scheduledTime: null,
      isActive: true,
      emoji: '🐹',
      createdAt: '2026-03-01T00:00:00Z',
    },
    {
      id: 'task-5',
      familyId: 'family-1',
      createdBy: 'parent-mama',
      assignedTo: 'child-kiko',
      title: 'たぴのトイレ掃除',
      description: 'たぴのトイレをきれいにしよう',
      category: 'chore',
      pointsValue: 20,
      frequency: 'daily',
      scheduledTime: null,
      isActive: true,
      emoji: '✨',
      createdAt: '2026-03-01T00:00:00Z',
    },
    {
      id: 'task-6',
      familyId: 'family-1',
      createdBy: 'parent-papa',
      assignedTo: 'child-kiko',
      title: '食器を洗う',
      description: '夕食後にお皿を洗おう',
      category: 'chore',
      pointsValue: 15,
      frequency: 'daily',
      scheduledTime: '19:30',
      isActive: true,
      emoji: '🍽️',
      createdAt: '2026-03-01T00:00:00Z',
    },
    {
      id: 'task-7',
      familyId: 'family-1',
      createdBy: 'parent-papa',
      assignedTo: 'child-kiko',
      title: '宿題をする',
      description: '帰ってきたらまず宿題！',
      category: 'habit',
      pointsValue: 20,
      frequency: 'weekday',
      scheduledTime: '16:00',
      isActive: true,
      emoji: '📝',
      createdAt: '2026-03-01T00:00:00Z',
    },
    {
      id: 'task-8',
      familyId: 'family-1',
      createdBy: 'parent-mama',
      assignedTo: 'child-kiko',
      title: '部屋の片付け',
      description: '寝る前に部屋をきれいにしよう',
      category: 'habit',
      pointsValue: 15,
      frequency: 'daily',
      scheduledTime: '20:30',
      isActive: true,
      emoji: '🧹',
      createdAt: '2026-03-01T00:00:00Z',
    },
  ],
  completions: [
    // 今日の達成
    {
      id: 'comp-1',
      taskId: 'task-1',
      userId: 'child-kiko',
      completedDate: today,
      selfInitiated: true,
      pointsEarned: 20, // 15 + 5 bonus
      note: '',
      createdAt: `${today}T06:30:00Z`,
    },
    {
      id: 'comp-2',
      taskId: 'task-2',
      userId: 'child-kiko',
      completedDate: today,
      selfInitiated: false,
      pointsEarned: 10,
      note: '',
      createdAt: `${today}T07:00:00Z`,
    },
    {
      id: 'comp-3',
      taskId: 'task-4',
      userId: 'child-kiko',
      completedDate: today,
      selfInitiated: false,
      pointsEarned: 15,
      note: '',
      createdAt: `${today}T08:00:00Z`,
    },
    // 昨日の達成
    {
      id: 'comp-4',
      taskId: 'task-1',
      userId: 'child-kiko',
      completedDate: yesterday,
      selfInitiated: true,
      pointsEarned: 20,
      note: '',
      createdAt: `${yesterday}T06:30:00Z`,
    },
    {
      id: 'comp-5',
      taskId: 'task-7',
      userId: 'child-kiko',
      completedDate: yesterday,
      selfInitiated: false,
      pointsEarned: 20,
      note: 'ちゃんとやった！',
      createdAt: `${yesterday}T16:00:00Z`,
    },
    {
      id: 'comp-6',
      taskId: 'task-6',
      userId: 'child-kiko',
      completedDate: yesterday,
      selfInitiated: false,
      pointsEarned: 15,
      note: '',
      createdAt: `${yesterday}T19:30:00Z`,
    },
  ],
  avatarItems: AVATAR_ITEMS,
  userAvatarItems: [
    {
      id: 'uai-1',
      userId: 'child-kiko',
      itemId: 'hair-pink-long',
      acquiredAt: '2026-03-15T00:00:00Z',
      isEquipped: true,
    },
    {
      id: 'uai-2',
      userId: 'child-kiko',
      itemId: 'eyes-smile',
      acquiredAt: '2026-03-16T00:00:00Z',
      isEquipped: false,
    },
    {
      id: 'uai-3',
      userId: 'child-kiko',
      itemId: 'shirt-red-hoody',
      acquiredAt: '2026-03-18T00:00:00Z',
      isEquipped: true,
    },
    {
      id: 'uai-4',
      userId: 'child-kiko',
      itemId: 'bg-pink',
      acquiredAt: '2026-03-20T00:00:00Z',
      isEquipped: true,
    },
  ],
  familyRules: [
    {
      id: 'rule-1',
      familyId: 'family-1',
      title: '朝のルール',
      content: '平日は6:30に起きる。自分で起きられたらボーナスポイント！',
      createdBy: 'parent-papa',
      createdAt: '2026-03-21T00:00:00Z',
    },
    {
      id: 'rule-2',
      familyId: 'family-1',
      title: 'たぴのお世話',
      content: '毎日ごはんとトイレ掃除をする。忘れたときはパパかママに言う。',
      createdBy: 'parent-mama',
      createdAt: '2026-03-21T00:00:00Z',
    },
    {
      id: 'rule-3',
      familyId: 'family-1',
      title: '週末ルール',
      content: '平日に全部達成できたら週末は自由時間が増える！',
      createdBy: 'parent-papa',
      createdAt: '2026-03-21T00:00:00Z',
    },
  ],
  currentUserId: null,
  currentFamilyId: null,
}
